# Before Build
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

# Branches to build
branches:
  only:
    - develop
    - master
    - main
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - tools -> recipe.cake, tools\packages.config

# Environment configuration
image: Visual Studio 2019

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/
